spec:
  containers:
    - image: brontosaurus/green:x.x.x
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          path: /health
          port: 8500
        initialDelaySeconds: 10
        periodSeconds: 10
      ports:
        - containerPort: 8500
          name: brontosaurus-green-port
          protocol: TCP
      env:
        - name: NODE_ENV
          value: production
        - name: BRONTOSAURUS_DATABASE
          value: <MONGO-DB-URL>
