spec:
  containers:
    - image: brontosaurus/red:x.x.x
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          path: /health
          port: 9000
        initialDelaySeconds: 10
        periodSeconds: 10
      ports:
        - containerPort: 9000
          name: brontosaurus-red-port
          protocol: TCP
      env:
        - name: NODE_ENV
          value: production
        - name: PORTAL_PATH
          value: <PORTAL-HTTPS-URL>
        - name: BRONTOSAURUS_DATABASE
          value: <MONGO-DB-URL>
